# Generated by Django 4.2 on 2025-02-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='Coupon',
            field=models.ManyToManyField(blank=True, to='store.coupon'),
        ),
    ]
