# Generated by Django 4.2 on 2025-02-17 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cartorderitem_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='Coupon',
            new_name='coupon',
        ),
    ]
